--
-- PostgreSQL database dump
--


-- Dumped from database version 15.17
-- Dumped by pg_dump version 18.0


CREATE TABLE public.adjuntos (
    id bigint NOT NULL,
    datos oid NOT NULL,
    nombre_archivo character varying(255),
    subido_en timestamp(6) without time zone,
    tipo_contenido character varying(255),
    elemento_checklist_id bigint,
    proyecto_id bigint,
    subido_por_id bigint
);


--
-- TOC entry 214 (class 1259 OID 16385)
-- Name: adjuntos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.adjuntos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adjuntos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16394)
-- Name: bitacora_auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bitacora_auditoria (
    id bigint NOT NULL,
    accion character varying(255) NOT NULL,
    detalle character varying(500),
    fecha timestamp(6) without time zone NOT NULL,
    usuario character varying(255) NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 16393)
-- Name: bitacora_auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bitacora_auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bitacora_auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16402)
-- Name: catalogo_elementos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catalogo_elementos (
    id bigint NOT NULL,
    champion character varying(255),
    codigo character varying(255),
    etapa_visual character varying(255),
    fase character varying(255),
    grupo character varying(255),
    nombre character varying(255),
    requerido boolean NOT NULL,
    tipo_input character varying(255)
);


--
-- TOC entry 218 (class 1259 OID 16401)
-- Name: catalogo_elementos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.catalogo_elementos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogo_elementos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16410)
-- Name: elemento_checklist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.elemento_checklist (
    id bigint NOT NULL,
    champion character varying(255),
    codigo character varying(255),
    comentario character varying(255),
    control_entregable character varying(255),
    es_main_event boolean NOT NULL,
    estado character varying(255),
    etapa_visual character varying(255),
    fase character varying(255),
    fecha_plan date,
    fecha_real date,
    grupo character varying(255),
    nombre character varying(255),
    score character varying(255),
    tipo_input character varying(255),
    catalogo_id bigint,
    proyecto_id bigint
);


--
-- TOC entry 220 (class 1259 OID 16409)
-- Name: elemento_checklist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.elemento_checklist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elemento_checklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16418)
-- Name: firmas_etapa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.firmas_etapa (
    id bigint NOT NULL,
    etapa integer,
    fecha_firma timestamp(6) without time zone,
    nombre_completo character varying(255),
    rol character varying(255),
    username character varying(255),
    proyecto_id bigint
);


--
-- TOC entry 222 (class 1259 OID 16417)
-- Name: firmas_etapa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.firmas_etapa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.firmas_etapa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16426)
-- Name: hitos_proyecto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hitos_proyecto (
    id bigint NOT NULL,
    etapa_asociada character varying(255),
    fecha date,
    nombre character varying(255),
    porcentaje_objetivo integer,
    proyecto_id bigint
);


--
-- TOC entry 224 (class 1259 OID 16425)
-- Name: hitos_proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hitos_proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hitos_proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16434)
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    autor_accion character varying(255),
    autor_departamento character varying(255),
    fecha_creacion timestamp(6) without time zone,
    leida boolean NOT NULL,
    link character varying(255),
    mensaje character varying(255),
    tipo character varying(255),
    titulo character varying(255),
    usuario_destino character varying(255),
    destinatario_id bigint
);


--
-- TOC entry 226 (class 1259 OID 16433)
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16442)
-- Name: proyectos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos (
    id bigint NOT NULL,
    archivado boolean NOT NULL,
    cliente character varying(255),
    es_historico boolean,
    fase_actual character varying(255),
    fecha_buyoff date,
    fecha_car date,
    fecha_inicio date,
    fecha_sop date,
    fecha_transit date,
    finance_manager character varying(255),
    hr_manager character varying(255),
    lider_proyecto character varying(255),
    materials_manager character varying(255),
    nombre character varying(255),
    numero_parte character varying(255),
    operations_manager character varying(255),
    process_engineer character varying(255),
    project_engineer character varying(255),
    project_leader character varying(255),
    quality_engineer character varying(255),
    quality_manager character varying(255),
    scs_manager character varying(255),
    sop date
);


--
-- TOC entry 228 (class 1259 OID 16441)
-- Name: proyectos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16450)
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL
);


--
-- TOC entry 230 (class 1259 OID 16449)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16455)
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_roles (
    usuario_id bigint NOT NULL,
    rol_id bigint NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 16461)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    correo character varying(255) NOT NULL,
    departamento character varying(255),
    habilitado boolean,
    nombre_completo character varying(255),
    contrasena character varying(255) NOT NULL,
    password_changed boolean,
    reset_token character varying(255),
    reset_token_expiration timestamp(6) without time zone,
    username character varying(255) NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 16460)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3310 (class 2606 OID 16392)
-- Name: adjuntos adjuntos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos
    ADD CONSTRAINT adjuntos_pkey PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 16400)
-- Name: bitacora_auditoria bitacora_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bitacora_auditoria
    ADD CONSTRAINT bitacora_auditoria_pkey PRIMARY KEY (id);


--
-- TOC entry 3314 (class 2606 OID 16408)
-- Name: catalogo_elementos catalogo_elementos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catalogo_elementos
    ADD CONSTRAINT catalogo_elementos_pkey PRIMARY KEY (id);


--
-- TOC entry 3316 (class 2606 OID 16416)
-- Name: elemento_checklist elemento_checklist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.elemento_checklist
    ADD CONSTRAINT elemento_checklist_pkey PRIMARY KEY (id);


--
-- TOC entry 3318 (class 2606 OID 16424)
-- Name: firmas_etapa firmas_etapa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firmas_etapa
    ADD CONSTRAINT firmas_etapa_pkey PRIMARY KEY (id);


--
-- TOC entry 3320 (class 2606 OID 16432)
-- Name: hitos_proyecto hitos_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hitos_proyecto
    ADD CONSTRAINT hitos_proyecto_pkey PRIMARY KEY (id);


--
-- TOC entry 3322 (class 2606 OID 16440)
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- TOC entry 3324 (class 2606 OID 16448)
-- Name: proyectos proyectos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT proyectos_pkey PRIMARY KEY (id);


--
-- TOC entry 3326 (class 2606 OID 16454)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3332 (class 2606 OID 16471)
-- Name: usuarios ukcdmw5hxlfj78uf4997i3qyyw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);


--
-- TOC entry 3328 (class 2606 OID 16469)
-- Name: roles ukldv0v52e0udsh2h1rs0r0gw1n; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukldv0v52e0udsh2h1rs0r0gw1n UNIQUE (nombre);


--
-- TOC entry 3334 (class 2606 OID 16473)
-- Name: usuarios ukm2dvbwfge291euvmk6vkkocao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username);


--
-- TOC entry 3330 (class 2606 OID 16459)
-- Name: usuario_roles usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (usuario_id, rol_id);


--
-- TOC entry 3336 (class 2606 OID 16467)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 3340 (class 2606 OID 16494)
-- Name: elemento_checklist fk6nbrxphhn1p009g7t8is3cnys; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.elemento_checklist
    ADD CONSTRAINT fk6nbrxphhn1p009g7t8is3cnys FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- TOC entry 3342 (class 2606 OID 16499)
-- Name: firmas_etapa fk8vaut8k8yiil1c2pif2wrh52v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firmas_etapa
    ADD CONSTRAINT fk8vaut8k8yiil1c2pif2wrh52v FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- TOC entry 3345 (class 2606 OID 16514)
-- Name: usuario_roles fkbt9i9yrb9ug88xnh82n9m60pr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fkbt9i9yrb9ug88xnh82n9m60pr FOREIGN KEY (rol_id) REFERENCES public.roles(id);


--
-- TOC entry 3337 (class 2606 OID 16474)
-- Name: adjuntos fkbtyepfqum8rnqr07wxvvcr1ms; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos
    ADD CONSTRAINT fkbtyepfqum8rnqr07wxvvcr1ms FOREIGN KEY (elemento_checklist_id) REFERENCES public.elemento_checklist(id);


--
-- TOC entry 3338 (class 2606 OID 16484)
-- Name: adjuntos fkdauso575t9y0tnd8ktxngtulh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos
    ADD CONSTRAINT fkdauso575t9y0tnd8ktxngtulh FOREIGN KEY (subido_por_id) REFERENCES public.usuarios(id);


--
-- TOC entry 3341 (class 2606 OID 16489)
-- Name: elemento_checklist fkhnh10x5btbyapt57obiqd3dl7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.elemento_checklist
    ADD CONSTRAINT fkhnh10x5btbyapt57obiqd3dl7 FOREIGN KEY (catalogo_id) REFERENCES public.catalogo_elementos(id);


--
-- TOC entry 3339 (class 2606 OID 16479)
-- Name: adjuntos fkjn2epflqiggrxg7yeofkqor41; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos
    ADD CONSTRAINT fkjn2epflqiggrxg7yeofkqor41 FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- TOC entry 3343 (class 2606 OID 16504)
-- Name: hitos_proyecto fkm631g18qdkant1cnc7hmhn8ab; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hitos_proyecto
    ADD CONSTRAINT fkm631g18qdkant1cnc7hmhn8ab FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- TOC entry 3344 (class 2606 OID 16509)
-- Name: notificaciones fkrxqukj4ow44h862qlbgl54ij2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fkrxqukj4ow44h862qlbgl54ij2 FOREIGN KEY (destinatario_id) REFERENCES public.usuarios(id);


--
-- TOC entry 3346 (class 2606 OID 16519)
-- Name: usuario_roles fkuu9tea04xb29m2km5lwe46ua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fkuu9tea04xb29m2km5lwe46ua FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


-- Completed on 2026-03-25 14:02:10

--
-- PostgreSQL database dump complete
--


