services:
  db:
    image: postgres:15-alpine
    container_name: johnson_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    #Solo la 'app' puede verlo internamente
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]      
      interval: 10s
      timeout: 5s
      retries: 5
    #Rotación de logs para evitar saturación de disco
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johnson_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_BASE_URL: ${APP_BASE_URL}
      #Optimización de rendimiento UI en producción
      SPRING_THYMELEAF_CACHE: "true" 
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    volumes:
      - ./backups:/app/backups
      - ./evidencias:/app/evidencias
    restart: always
    #Rotación de logs (Máximo 50MB en total de logs almacenados)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    #Contención de recursos (Previene el OOM Killer de Linux)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: johnson_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    #Rotación de logs web (Evita que el log de accesos llene el disco)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"