services:
  db:
    image: postgres:15-alpine
    container_name: johnson_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]      
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johnson_app
    ports:
      - "8443:8080" # El puente vital hacia tu Nginx Nativo
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_THYMELEAF_CACHE=true 
    volumes:
      - ./backups:/app/backups
      - ./evidencias:/app/evidencias
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M