-- liquibase formatted sql

-- changeset franco:1
CREATE TABLE adjuntos (id bigint generated by default as identity, datos oid not null, nombre_archivo varchar(255), subido_en timestamp(6), tipo_contenido varchar(255), elemento_checklist_id bigint, proyecto_id bigint, subido_por_id bigint, primary key (id));
CREATE TABLE bitacora_auditoria (id bigint generated by default as identity, accion varchar(255) not null, detalle varchar(500), fecha timestamp(6) not null, usuario varchar(255) not null, primary key (id));
CREATE TABLE catalogo_elementos (id bigint generated by default as identity, champion varchar(255), codigo varchar(255), etapa_visual varchar(255), fase varchar(255), grupo varchar(255), nombre varchar(255), requerido boolean not null, tipo_input varchar(255), primary key (id));
CREATE TABLE elemento_checklist (id bigint generated by default as identity, champion varchar(255), codigo varchar(255), comentario varchar(255), control_entregable varchar(255), es_main_event boolean not null, estado varchar(255), etapa_visual varchar(255), fase varchar(255), fecha_plan date, fecha_real date, grupo varchar(255), nombre varchar(255), score varchar(255), tipo_input varchar(255), catalogo_id bigint, proyecto_id bigint, primary key (id));
CREATE TABLE firmas_etapa (id bigint generated by default as identity, etapa integer, fecha_firma timestamp(6), nombre_completo varchar(255), rol varchar(255), username varchar(255), proyecto_id bigint, primary key (id));
CREATE TABLE hitos_proyecto (id bigint generated by default as identity, etapa_asociada varchar(255), fecha date, nombre varchar(255), porcentaje_objetivo integer, proyecto_id bigint, primary key (id));
CREATE TABLE notificaciones (id bigint generated by default as identity, autor_accion varchar(255), fecha_creacion timestamp(6), leida boolean not null, link varchar(255), mensaje varchar(255), tipo varchar(255), titulo varchar(255), usuario_destino varchar(255), destinatario_id bigint, primary key (id));
CREATE TABLE proyectos (id bigint generated by default as identity, cliente varchar(255), fecha_buyoff date, fecha_car date, fecha_inicio date, fecha_sop date, fecha_transit date, finance_manager varchar(255), hr_manager varchar(255), lider_proyecto varchar(255), materials_manager varchar(255), nombre varchar(255), numero_parte varchar(255), operations_manager varchar(255), process_engineer varchar(255), project_engineer varchar(255), project_leader varchar(255), quality_engineer varchar(255), quality_manager varchar(255), scs_manager varchar(255), sop date, primary key (id));
CREATE TABLE roles (id bigint generated by default as identity, nombre varchar(255) not null, primary key (id));
CREATE TABLE usuario_roles (usuario_id bigint not null, rol_id bigint not null, primary key (usuario_id, rol_id));
CREATE TABLE usuarios (id bigint generated by default as identity, correo varchar(255) not null, habilitado boolean, nombre_completo varchar(255), contrasena varchar(255) not null, password_changed boolean, reset_token varchar(255), reset_token_expiration timestamp(6), username varchar(255) not null, primary key (id));

ALTER TABLE IF EXISTS roles ADD CONSTRAINT UKldv0v52e0udsh2h1rs0r0gw1n UNIQUE (nombre);
ALTER TABLE IF EXISTS usuarios ADD CONSTRAINT UKcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);
ALTER TABLE IF EXISTS usuarios ADD CONSTRAINT UKm2dvbwfge291euvmk6vkkocao UNIQUE (username);

ALTER TABLE IF EXISTS adjuntos ADD CONSTRAINT FKbtyepfqum8rnqr07wxvvcr1ms FOREIGN KEY (elemento_checklist_id) REFERENCES elemento_checklist;
ALTER TABLE IF EXISTS adjuntos ADD CONSTRAINT FKjn2epflqiggrxg7yeofkqor41 FOREIGN KEY (proyecto_id) REFERENCES proyectos;
ALTER TABLE IF EXISTS adjuntos ADD CONSTRAINT FKdauso575t9y0tnd8ktxngtulh FOREIGN KEY (subido_por_id) REFERENCES usuarios;
ALTER TABLE IF EXISTS elemento_checklist ADD CONSTRAINT FKhnh10x5btbyapt57obiqd3dl7 FOREIGN KEY (catalogo_id) REFERENCES catalogo_elementos;
ALTER TABLE IF EXISTS elemento_checklist ADD CONSTRAINT FK6nbrxphhn1p009g7t8is3cnys FOREIGN KEY (proyecto_id) REFERENCES proyectos;
ALTER TABLE IF EXISTS firmas_etapa ADD CONSTRAINT FK8vaut8k8yiil1c2pif2wrh52v FOREIGN KEY (proyecto_id) REFERENCES proyectos;
ALTER TABLE IF EXISTS hitos_proyecto ADD CONSTRAINT FKm631g18qdkant1cnc7hmhn8ab FOREIGN KEY (proyecto_id) REFERENCES proyectos;
ALTER TABLE IF EXISTS notificaciones ADD CONSTRAINT FKrxqukj4ow44h862qlbgl54ij2 FOREIGN KEY (destinatario_id) REFERENCES usuarios;
ALTER TABLE IF EXISTS usuario_roles ADD CONSTRAINT FKbt9i9yrb9ug88xnh82n9m60pr FOREIGN KEY (rol_id) REFERENCES roles;
ALTER TABLE IF EXISTS usuario_roles ADD CONSTRAINT FKuu9tea04xb29m2km5lwe46ua FOREIGN KEY (usuario_id) REFERENCES usuarios;